[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"

[[repos.hooks]]
id = "trailing-whitespace"

[[repos.hooks]]
id = "end-of-file-fixer"

[[repos.hooks]]
id = "check-toml"

[[repos.hooks]]
id = "check-added-large-files"

[[repos.hooks]]
id = "detect-private-key"

[[repos]]
repo = "https://github.com/antonbabenko/pre-commit-terraform"
rev = "v1.105.0"

[[repos.hooks]]
id = "terraform_fmt"
args = ["--args=-recursive"]

[[repos.hooks]]
id = "terraform_validate"
env = {AWS_PROFILE = "otto-management"}

[[repos]]
repo = "https://github.com/gitleaks/gitleaks"
rev = "v8.30.1"

[[repos.hooks]]
id = "gitleaks-system"
pass_filenames = false
